"""Brand keyword inventory supplied in Keywords for Platform level Lead scanning.xlsx.

This file preserves the source terms.  Matching safety (broad-term handling,
word boundaries, year/country noise) belongs in services/brands.py so the
inventory remains auditable against the workbook.
"""
from __future__ import annotations

BRAND_KEYWORDS: dict[str, tuple[str, ...]] = {
    'Green Foundation': (
        'Climate Adaptation',
        'Climate Mitigation',
        'ESG',
        'Sustainability',
        'Climate Smart Agriculture',
        'Climate and Food',
        'Climate and Health',
        'Climate Action',
        'Climate Resilience',
        'Heat Stress',
        'Climate Change',
        'Regenerative Agriculture',
        'Climate Smart Products',
        'Climate Innovation',
        'Regenerative agriculture India',
        'Regenerative landscape India',
        'Regen agriculture smallholder farmers',
        'Regenerative food systems India',
        'Commons governance India',
        'Commons-based agroecology',
        'Agroecology India',
        'Agroecological transition India',
        'Agroecology grant India 2025',
        'Agroecology innovation fund 2025',
        'Agroecology network India membership',
        'Agroecology transition consulting India',
        'Biodiversity credits India',
        'Biodiversity conservation grant India',
        'Biodiversity monitoring methodology consultant',
        'Agrobiodiversity conservation India',
        'Agrobiodiversity digital repository',
        'Agrobiodiversity policy India',
        'Nature-based solutions finance India',
        'Nature markets India 2025',
        'Ecosystem service payments smallholders',
        'Ecosystem credits agrobiodiversity',
        'Multi-dimensional ecosystem credits',
        'Voluntary carbon market smallholder',
        'Carbon Credit Trading Scheme India',
        'Carbon MRV methodology consultant India',
        'Pre-issuance carbon credits India',
        'Blended finance agroecology India',
        'Plan Vivo methodology agroecology',
        'TNFD India agriculture',
        'Green Credit Programme India agriculture methodology',
        'Kunming-Montreal biodiversity finance',
        'Social procurement India agriculture',
        'SEBI BRSR value chain sustainability',
        'SEBI BRSR agriculture advisory',
        'BRSR sustainability disclosure agriculture',
        'Scope 3 agricultural supply chain India',
        'Regenerative sourcing corporate India',
        'ESG supply chain smallholder farmers India',
        'Sustainable procurement FPO India',
        'Indigenous crop procurement corporate',
        'Organic supply chain aggregation India',
        'Corporate sustainable sourcing India 2025',
        'Corporate nature positive agriculture India',
        'Corporate regenerative sourcing India',
        'Corporate field immersion programme India',
        'CSR agriculture India partner NGO',
        'ESG agriculture partner India',
        'ITC sustainable sourcing NGO',
        'HUL sustainable agriculture India',
        'Nestl\xe9 responsible sourcing partner India',
        'Food systems transformation grant',
        'Food systems innovation challenge India',
        'Food systems assessment India',
        'Food systems coalition India',
        'Climate adaptation smallholder farmers grant',
        'Climate smart agriculture network India',
        'Rural livelihoods climate resilience RFP',
        'Indigenous knowledge documentation grant',
        'Women farmers empowerment grant India',
        'Seed sovereignty funding opportunity',
        'Seed sovereignty network membership',
        'Seed sovereignty legislation India',
        'Commons governance grant India',
        'Landscape planning consultancy India',
        'Regenerative landscape planning India',
        'FPO development consulting India',
        'FPO digital marketplace India',
        'Farmer producer organisation network India',
        'M&E framework design agriculture India',
        'Participatory research consultant India',
        'Theory of change development NGO India',
        'Impact evaluation regenerative agriculture',
        'Impact measurement platform agriculture India',
        'Natural farming programme Karnataka',
        'Natural farming programme India',
        'Paramparagat Krishi Vikas Yojana implementation',
        'PM POSHAN indigenous grain procurement',
        'MGNREGA watershed agroecology convergence',
        'State climate adaptation agriculture programme',
        'Karnataka agriculture department consultancy',
        'Madhya Pradesh natural farming tender',
        'National Agroecology Mission India',
        'NCNF member organisation call',
        'NABARD natural farming grant',
        'NABARD agroecology India',
        'IFAD India smallholder grant',
        'ADB agroecology India',
        'GIZ sustainable agriculture India call for proposals',
        'FCDO food systems India',
        'CGIAR agroecology grant',
        'CGIAR research partner India',
        'CGIAR innovation challenge',
        'Azim Premji Foundation agriculture grant',
        'Rohini Nilekani Philanthropies food systems',
        'Tata Trusts agriculture grant',
        'Ford Foundation food sovereignty India',
        'Rockefeller Foundation food systems grant',
        'Wellcome Trust food environment grant',
        'Echoing Green fellowship food systems',
        'Ashoka fellowship regenerative agriculture',
        'EIT Food innovation grant',
        'Commons.farm India partnership',
        'Digital public infrastructure agriculture India',
        'Farmer data platform India',
        'AI agriculture remote sensing India',
        'Satellite monitoring regenerative farming',
        'Geospatial landscape monitoring India partner',
        'AgTech social enterprise India',
        'Traceability platform indigenous crops',
        'Know Your Resilience platform partner',
        'GeM FPO social procurement',
        'ONDC farmer collective onboarding',
        'RRA Network India',
        'IFOAM India member',
        'PGSOC India',
        'Common Ground collaborative',
        'Agroecology collaborative India',
        'Regenerative agriculture collaborative India',
        'Social enterprise agriculture challenge India',
        'Impact investment agroecology India',
        'Venture philanthropy food systems India',
        'Call for proposals agroecology India 2025',
        'Expression of interest regenerative agriculture India',
        'Request for applications food systems India 2025',
        'Open call indigenous knowledge India',
        'Open call seed systems India',
        'Regen agriculture moonshot',
        'Regen agriculture platform India',
        'Regen landscape monitoring India',
        'Commons-based natural resource management India',
        'Community seed bank India',
        'Participatory guarantee system India',
        'Farmer scientist programme India',
        'Traditional ecological knowledge India',
        'Indigenous variety conservation India',
        'Nutritional security indigenous crops India',
        'Millet value chain India',
        'Indigenous crop value chain India',
        'Regen agriculture consulting India',
        'Regen agriculture evidence India',
        'Regen agriculture policy India',
        'Regen agriculture investment India',
        'Regen agriculture scale India',
    ),
    'Vrutti': (
        'Livelihood',
        'Climate Finance',
        'Entrepreneurship',
        'Social Entrepreneurship',
        'Regenerative Agriculture',
        'Blended Financing',
        'Agri Financing',
        'Commons',
        'Restoration',
        'Sustainable Agriculture',
        'Value Chain Studies',
        'Farm',
        'Non-Farm',
        'MSME',
        'FPO',
        'FPCs',
        'Women Entrepreneurship',
        'Farmer Livelihoods',
        'Livestock',
        'Fisheries',
        'Smallholder Agriculture',
    ),
    'Swasti': (
        'Public Health',
        'Health Systems Strengthening',
        'Climate and Health',
        'Livelihoods',
        'Nutrition',
        'Gender',
        'Digital Health',
        'Social Protection',
        'India',
        'SRHR',
        'Surveillance',
        'Primary Health',
        'AI and Health',
        'Evaluation',
        'Research',
        'Design',
        'Worker Well Being',
        'Food Security and Nutrition',
    ),
    'Upfront': (
        'Worker',
        'Community',
        'Urban',
        'Rural',
        'Formal',
        'Informal',
        'Supply Chain',
        'Textile',
        'Cotton',
        'Spice',
        'Workforce Wellbeing',
        'Employee Mental Wellness',
        'Workplace Wellbeing',
        'Employee Well Being',
        'Gender Equality in Workplace',
        'Gender Justice and Workplace Security',
        'Gender Sensitivity at Workplace',
        'Health and Wellness of Employees',
        'Healthy Workplace Environment',
        'Inclusion at Workplace',
        'Menstrual Hygiene Awareness',
        'Mental Health Support in the Workplace',
        'Mentorship Program for Employees',
        'Occupational Health and Environment',
        'Resilience Training at Work',
        'Skilled Workforce Development',
        'Social Well Being at Work',
        'Wellbeing at Work',
        'Wellness of Employees',
        'Women Safety in Workplace',
        'Workforce Empowerment',
        'Workplace Health Benefits',
        'Workplace Safety Measures',
        'Workplace Safety Programs',
        'Informal Workforce',
        'Factory Worker',
        'Factory Workforce',
        'Gig Worker',
        'Gig Workforce',
        'Textile Workforce',
        'Textile Worker',
        'Garment Worker',
        'Garment Workforce',
        'Retail Worker',
        'Manufacturing Worker',
        'Worker Resilience',
        'Work Ecosystem',
        'ESG',
        'BRSR',
        'Business and Human Rights',
    ),
}

SOURCE_KEYWORD_COUNTS = {
    'Green Foundation': 158,
    'Vrutti': 21,
    'Swasti': 18,
    'Upfront': 50,
}

BRANDS = tuple(BRAND_KEYWORDS)
