"""Keyword inventory supplied by the BD team (Keyword Searches Vertical Wise.xlsx).

Two separate things live here, and they are used differently:

  VERTICAL_KEYWORDS   drives classification — a keyword hit contributes to that
                      vertical's score in services/verticals.py.

  KEYWORD_INVENTORY   drives the search suggestions in the dashboard. These are
                      the terms the team actually searches by, grouped the way
                      they think about them, so they belong in the UI rather
                      than in the classifier.

Regenerated from the spreadsheet rather than hand-typed, so the two stay in
step. Edit the sheet and re-import instead of editing this file by hand.
"""
from __future__ import annotations

VERTICAL_KEYWORDS: dict[str, list[str]] = {
    "Health": [
        "Climate & Health",
        "Digital Health",
        "Evaluation",
        "Health care management",
        "Health Consulting",
        "Health Systems strengthening",
        "Maternal & Child Health",
        "Primary Health",
        "Research",
        "Training & Capacity Building"
    ],
    "Livelihood": [
        "Agriculture & Rural Development",
        "Education",
        "Energy",
        "Environment & Climate",
        "Fisheries & Aquaculture",
        "Food Systems & Livelihoods",
        "Fundraising & Grant Management",
        "HR & Employment",
        "Macro-Economy & Public Finance",
        "Monitoring & Evaluation",
        "Organizational Development",
        "Project Management",
        "Research & Innovation",
        "Sanitation & Hygiene",
        "Social Development",
        "Statistics and Data Analysis",
        "Training & Capacity Building",
        "Water"
    ],
    "E4C(Evidence for Change)": [
        "baseline study",
        "consulting",
        "CSR projects",
        "data collection",
        "endline study",
        "evaluation",
        "Impact assessment",
        "impact study",
        "longitudinal study",
        "midline study",
        "Monitoring & evaluation",
        "outcome harvesting.",
        "research project",
        "SROI study"
    ],
    "Innovative Finance": [
        "blended finance",
        "capital mobilisation",
        "catalytic capital",
        "catalytic finance",
        "climate finance",
        "concessional finance",
        "development finance",
        "development impact bond",
        "financial inclusion",
        "first-loss capital",
        "guarantee facility",
        "impact investing",
        "impact-linked finance",
        "inclusive finance",
        "innovative finance",
        "innovative financing mechanisms",
        "interest subvention",
        "investment readiness",
        "outcomes fund",
        "patient capital",
        "private capital mobilisation",
        "resilience finance",
        "results-based financing",
        "revolving grants",
        "social finance",
        "social impact investing",
        "structured finance",
        "sustainable finance",
        "technical assistance facility",
        "venture philanthropy"
    ],
    "Climate/Sustainability(ESG)": [
        "Afforestration",
        "Agriculture Value Chain",
        "Agro forestry",
        "Bio-diversity conservation",
        "Circular Apparel",
        "Circular Economy",
        "Circularity",
        "Climate Adaptation",
        "Climate Change",
        "Climate Mitigation",
        "Climate Resilience",
        "Climate Resilient Agriculture",
        "Climate Smart Agriculture",
        "Decarbonization",
        "Energy",
        "Environment and Climate",
        "ESG Reporting",
        "GHG emissions",
        "Habitat Conservation",
        "Heating and Cooling systems",
        "Impact Procurement",
        "Materiality Assessment",
        "Natural Farming",
        "Natural Resource Management",
        "Net Zero",
        "Organic Farming",
        "Pollution and Waste Management",
        "Private Sector Engagement",
        "Regenerative Agriculture",
        "Resilient Infrastructure",
        "Scope 1 Emissions",
        "Scope 3 Emissions",
        "Social Procurement",
        "Soil & Water Conservation.Food Security",
        "Sustainability",
        "Sustainability Reporting",
        "Sustainability Strategy",
        "Sustainable Agriculture",
        "Sustainable Livelihoods"
    ],
    "Worker Wellbeing": [
        "employee mental wellness",
        "employee well being initiatives",
        "employee well being programs",
        "employees well being",
        "gender equality at workplace in india",
        "gender equality workplace",
        "gender justice and workplace security",
        "gender sensitivity at workplace",
        "health and wellness of employees",
        "health working environment",
        "healthy workplace environment",
        "inclusion at workplace",
        "menstrual hygiene awareness campaign",
        "menstrual hygiene awareness program",
        "mental health support in the workplace",
        "mentorship program for employees",
        "Occupational health",
        "occupational health and environment",
        "Occupational safety",
        "promoting gender equality in the workplace",
        "resilience training at work",
        "skilled workforce development",
        "social well being at work",
        "well being for employees",
        "well being of workers",
        "wellbeing at work",
        "wellness of employees",
        "Women empowerment",
        "women safety in work place",
        "workforce empowerment",
        "workforce wellbeing",
        "workplace health benefits"
    ]
}

KEYWORD_INVENTORY: dict[str, list[str]] = {
    "Circularity": [
        "Circularity",
        "Circular Economy",
        "Food Systems",
        "Circular Agriculture",
        "Circular Apparel",
        "Circular Fashion"
    ],
    "SMEs": [
        "MSMEs",
        "Enterpreneurs",
        "Consumables (healthcare)",
        "Micro enterprises",
        "Women Owned Business",
        "Social Buisnesses"
    ],
    "Waste": [
        "Waste to Energy",
        "Pyrolysis",
        "Plastic Waste Management",
        "Plastic Recycling",
        "Zero Waste Solutions",
        "Ocean Plastics",
        "Landfill",
        "Reuse",
        "Bio-Fuels"
    ],
    "Resilience": [
        "Sustainable Livelihoods",
        "Sustainable Agriculture",
        "Coastal Vulnerability",
        "Resilience Building",
        "Resilient Communities",
        "Social Protection",
        "Community Resilience Building",
        "Resilient Infrastructure"
    ],
    "Ecology, Agriculture, Climate & Conservation": [
        "Scope 1 Emissions",
        "Scope 3 Emissions",
        "Climate Resilience",
        "Habitat Conservation",
        "Marine Protected Areas",
        "Clean Air",
        "Climate Change",
        "Bio-diversity conservation",
        "Conservation Agriculture",
        "Regenerative Agriculture",
        "Natural Farming",
        "Climate Resilient Agriculture",
        "Climate Smart Agriculture",
        "Organic Farming",
        "Agriculture Bio-Inputs",
        "Ecological Agriculture",
        "Forest Produce",
        "Blue Economy",
        "Safe Food to Consumers",
        "Farmer Rights",
        "Soil & Water Conservation",
        "Blue Ocean",
        "Food Security",
        "Agro forestry",
        "Afforestration",
        "Climate Mitigation",
        "Climate Adaptation",
        "Agri-processing",
        "Food Processing",
        "Producer Organisation",
        "Community Based Organisation",
        "Farmer Collectivisation",
        "Non Timber Forest Produce (NTFP)",
        "Forest Produce",
        "Agriculture Value Chain",
        "Disaster Mitigation",
        "Disaster Management",
        "Disaster Preparedness",
        "Pasture Land",
        "Net Zero",
        "Ponds",
        "Natural Resource Management"
    ],
    "Health": [
        "Vector Borne Diseases",
        "Health Systems Strengthening",
        "Primary Healthcare",
        "Adolescent & Health Well being",
        "Maternal & Child Health",
        "Sexual & Reproductive Health (SRHR)",
        "HIV/AIDS",
        "Tuberculosis (TB)",
        "Maternal & Neo-Natal Mortality",
        "Quality of care",
        "Pandemic",
        "Telemedicine",
        "Health Workers",
        "WASH",
        "Primary Care",
        "Palliative Care",
        "Digital Health",
        "Last mile health delivery",
        "Health procurement",
        "Living Equipment",
        "Point of Care Diagnostics",
        "Universal Health Coverage",
        "Mental Health",
        "Worker Health & Well Being",
        "Health Research",
        "Precision Health",
        "Water Borne Diseases",
        "Preventive Health",
        "Phygital",
        "Health Stack"
    ],
    "Funding": [
        "Blended Finance",
        "Innovation Finance",
        "Agri Bond",
        "Green Bond",
        "Seed Fund",
        "Catalytic Capital",
        "Gap Funding",
        "Evidence Research Funding",
        "Development Impact Bond",
        "Outcome Based Funding",
        "Concessional Grant",
        "Micro-Finance",
        "Credit Linkage",
        "Grants"
    ],
    "Leads": [
        "Tender",
        "Request for Proposal",
        "Request for Interest",
        "Expression of Interest",
        "Concept Note",
        "Value Chain Studies",
        "Monitoring & Evaluation",
        "Impact Assessment",
        "Outcome Assessment",
        "Baseline Assessment",
        "Midterm Assessment",
        "Endline Assessment",
        "Impact Evaluation",
        "Quantitative Research",
        "Qualitative Research",
        "Incubation Support",
        "Policy Evaluation",
        "Country Strategy Assessment",
        "Award",
        "Nominations",
        "Bid",
        "APS",
        "Call for Papers"
    ],
    "Communities": [
        "Vulnerable Communities",
        "Children",
        "Persons with Disabilities",
        "Farmers",
        "Fishermen",
        "Migrant Workers",
        "Women",
        "Unorganised workers",
        "Informal workers",
        "Street vendors",
        "Women owned buisinesses",
        "Gender based violence",
        "Factory Workers",
        "Unorganised Sector",
        "Workforce",
        "Frontline Worker",
        "Women Empowerment"
    ],
    "Other (standalone or with prefix/suffix of our focus areas)": [
        "Coalition",
        "Alliance",
        "Fund",
        "Collaborative Action",
        "Market System Development",
        "Market Linkage",
        "Market Access",
        "Financial Inclusion",
        "Private Sector Engagement",
        "Inclusive Development"
    ]
}


ALL_SEARCH_TERMS: list[str] = sorted(
    {t for group in KEYWORD_INVENTORY.values() for t in group}
    | {t for group in VERTICAL_KEYWORDS.values() for t in group},
    key=str.lower,
)
